### ISSUE TITLE
Error: config_resolved.pop("_target_") when trying to generate.

### ISSUE THREAD

**Issue by maxenko** [victorchall/genmoai-smol#1]
Any idea what this might be caused by?

```
(.venv) root@cffcc51e77c1:/workspace/genmoai_smol# python -m mochi_preview.gradio_ui --model_dir "../models"
* Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
2024-10-29 19:50:23,332 WARNING worker.py:1481 -- SIGTERM handler is not set because current thread is not the main thread.
2024-10-29 19:50:24,313 INFO worker.py:1816 -- Started a local Ray instance.
(T2VSynthMochiModel pid=22226) Timing load_text_encs
(T2VSynthMochiModel pid=22226) Timing load_vae
(T2VSynthMochiModel pid=22226) Timing construct_dit
(T2VSynthMochiModel pid=22226) Exception raised in creation task: The actor died because of an error raised in its creation task, ray::T2VSynthMochiModel.__init__() (pid=22226, ip=172.17.0.3, actor_id=49d7d4d7d5ee75f1478d587301000000, repr=<mochi_preview.t2v_synth_mochi.T2VSynthMochiModel object at 0x7f9582bad0f0>)
(T2VSynthMochiModel pid=22226)   File "/workspace/genmoai_smol/.venv/lib/python3.10/site-packages/mochi_preview/t2v_synth_mochi.py", line 282, in __init__
(T2VSynthMochiModel pid=22226)     config_resolved.pop("_target_")
(T2VSynthMochiModel pid=22226) KeyError: '_target_'
Traceback (most recent call last):
  File "/workspace/genmoai_smol/.venv/lib/python3.10/site-packages/gradio/queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
  File "/workspace/genmoai_smol/.venv/lib/python3.10/site-packages/gradio/route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "/workspace/genmoai_smol/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 2018, in process_api
    result = await self.call_function(
  File "/workspace/genmoai_smol/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 1567, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/workspace/genmoai_smol/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/workspace/genmoai_smol/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "/workspace/genmoai_smol/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "/workspace/genmoai_smol/.venv/lib/python3.10/site-packages/gradio/utils.py", line 846, in wrapper
    response = f(*args, **kwargs)
  File "/workspace/genmoai_smol/.venv/lib/python3.10/site-packages/mochi_preview/infer.py", line 99, in generate_video
    load_model()
  File "/workspace/genmoai_smol/.venv/lib/python3.10/site-packages/mochi_preview/infer.py", line 59, in load_model
    model = MochiWrapper(
  File "/workspace/genmoai_smol/.venv/lib/python3.10/site-packages/mochi_preview/handler.py", line 25, in __init__
    ray.get(worker.__ray_ready__.remote())
  File "/workspace/genmoai_smol/.venv/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/workspace/genmoai_smol/.venv/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/workspace/genmoai_smol/.venv/lib/python3.10/site-packages/ray/_private/worker.py", line 2745, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/workspace/genmoai_smol/.venv/lib/python3.10/site-packages/ray/_private/worker.py", line 903, in get_objects
    raise value
ray.exceptions.ActorDiedError: The actor died because of an error raised in its creation task, ray::T2VSynthMochiModel.__init__() (pid=22226, ip=172.17.0.3, actor_id=49d7d4d7d5ee75f1478d587301000000, repr=<mochi_preview.t2v_synth_mochi.T2VSynthMochiModel object at 0x7f9582bad0f0>)
  File "/workspace/genmoai_smol/.venv/lib/python3.10/site-packages/mochi_preview/t2v_synth_mochi.py", line 282, in __init__
    config_resolved.pop("_target_")
KeyError: '_target_'
```

**Comment by ShafinH** [comment]
You can just comment that line out since it seems to be doing nothing anyways
